### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by tebeka** [gopherconil/2019#12]
Need a logo (thinking of Gopher from https://gopherize.me with a "Tembel" hat).

**Comment by tebeka** [comment]
Talking to Tomer Shilo (shilotomer2@gmail.com) who's wants to get experience in design. He's interested.

**Comment by tebeka** [comment]
[לוגו Gopher Israel.pdf](https://github.com/gopherconil/2019/files/2248733/Gopher.Israel.pdf)

**Comment by richardbmx** [comment]
@tebeka  Hello my name is Richard I am a graphic designer and I love making contributions for open source projects, I see that you do not have a defined logo for your application. If you want I can do it for you without any problem...

**Comment by tebeka** [comment]
Thanks @richardbmx. We already have someone working on it.

**Comment by tebeka** [comment]
![logo](https://user-images.githubusercontent.com/87697/43712433-d694a97a-997e-11e8-9884-8814fe88ffbe.png)
